server:
  port: 8765
  
spring:
  application:
    name: eureka-server
  main:
    banner-mode: 'OFF'
  security:
    user:
      name: admin
      password: 123456
                 
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 60000 #清理间隔（默认毫秒）
    enable-self-preservation: true #false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
  client:
    register-with-eureka: true # 表示是否将自己注册到Eureka Server，默认为true
    fetch-registry: true  # 表示是否从Eureka Server获取注册信息，默认为true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/    